# Generated by Django 5.2 on 2025-04-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerialimage',
            name='is_classified',
            field=models.BooleanField(default=False),
        ),
    ]
