# Generated by Django 5.2 on 2025-04-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_aerialimage_is_classified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aerialimage',
            name='is_classified',
        ),
    ]
